### ISSUE TITLE
XGBoost experiments generalization

### ISSUE THREAD

**Issue by AnaRisnoveanu** [automl/NASLib#181]
This question is more about what the paper ("NAS-Bench-Suite-Zero: Accelerating Research on Zero Cost Proxies") describes in Table 10 from Appendix D. It is still unclear to me whether the XGBoost was trained on ZC scores and/or encodings on one single benchmark and then tested on the rest of the benchmarks or XGBoost was trained on a subset of benchmark models and later tested on models from the same benchmark.

**Comment by Neonkraft** [comment]
Hi @AnaRisnoveanu!

Thank you for your interest in our paper! The XGBoost was trained on a subset of models from one benchmark, and then tested on other models from the same benchmark. Since the encodings are searchspace-specific, we can't train on one and test on another.

I hope this helps!

Best,
Arjun

**Comment by AnaRisnoveanu** [comment]
Thank you for the clarification!
